---
version: 2
jobs:
  node-10: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y p7zip-full \
            osslsigncode \
            nsis \
            awscli
      - restore_cache: &restore_cache
          keys:
            - v3-yarn-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v3-yarn-{{checksum ".circleci/config.yml"}}
      - run: yarn
      - run: yarn test
  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: *restore_cache
      - run: yarn global add @oclif/semantic-release@3 semantic-release@15
      - run: yarn --frozen-lockfile
      - run: |
          export PATH=/usr/local/share/.config/yarn/global/node_modules/.bin:$PATH
          semantic-release -e @oclif/semantic-release
      - save_cache:
          key: v3-yarn-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn

workflows:
  version: 2
  "@oclif/plugin-update":
    jobs:
      - node-10
      - release:
          context: org-global
          filters:
            branches: {only: master}
          requires:
            - node-10
